### ISSUE TITLE
"development" version in a release

### ISSUE THREAD

**Issue by jgawor** [tektoncd/dashboard#1065]
I see the following in https://github.com/tektoncd/dashboard/releases/download/v0.5.2/openshift-tekton-dashboard-release.yaml

```
...
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tekton-dashboard
    version: development
  name: tekton-dashboard
  namespace: tekton-pipelines
...
```

The `version` field seems to be invalid for an actual release.
