### ISSUE TITLE
EventListeners, Interceptors: option to NOT show CEL interceptor details

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/dashboard#1129]
If a CEL interceptor handles a sensitive value (i.e. like in a comparison) its exposed in the clear in the dashboard. Might be nice to have an option to obfuscate or toggle displaying on/off interceptor details when the dashboard is installed.

**Comment by a-roberts** [comment]
Yeah this is a good idea, so a few things about how we could implement this

1) Option at install time?
2) A switch on the page itself?
3) Something more intelligent, like having a known sensitive field name and if you use that we won't display the values?

Open to more suggestions too, @AlanGreene FYI

**Comment by AlanGreene** [comment]
If the concern is around surfacing sensitive information in the UI we would also need to disable the raw YAML view of the EventListener.

I wonder if there's any guidance in [tektoncd/triggers](https://github.com/tektoncd/triggers) on how to handle sensitive values like this?

**Comment by bigkevmcd** [comment]
One possibility, might be to add an extension function "secretValue(ns, name, key)" which would find a named secret, and return the string value.

**Comment by a-roberts** [comment]
> One possibility, might be to add an extension function "secretValue(ns, name, key)" which would find a named secret, and return the string value.

Yeah 👍 this sounds good to me, and I'm wondering if this is specific to just using CEL style interceptors (surely not)

**Comment by bigkevmcd** [comment]
@bitsofinfo can you describe the specifics of what you're matching on?

**Comment by bitsofinfo** [comment]
was thinking same thing as @bigkevmcd something that can let you inject a legit k8s secret into an expression (by name) via some little function like that.

use-case, a shared secret/string that is simply conveyed via a header between the remote hook that is calling the EventListener w/ JSON and the CEl interceptors that validate it.

**Comment by dibyom** [comment]
> I wonder if there's any guidance in tektoncd/triggers on how to handle sensitive values like this (i.e. so they can be referenced safely rather than inlining them)?

For secret values, we usually take a reference to a k8s secret (like in GitHub/Gtlab interceptors).

> use-case, a shared secret/string that is simply conveyed via a header between the remote hook that is calling the EventListener w/ JSON and the CEL interceptors that validate it.

This is almost exactly what the Gitlab interceptor does...wonder if it makes sense to have a generic shared secret interceptor like that

**Comment by bigkevmcd** [comment]
@dibyom that would be fairly easy to do, the question is "what algorithm"?

Some are HMAC, some are simple constant-time string comparisons.

Something vaguely like this:
```yaml
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-interceptor
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      interceptors:
        - sharedsecret:
            header: X-My-Header
            secret:
              name: my-secret
              namespace: my-ns
              key: interceptor-secret
            algorithm: hmac | compare
```
The complexity comes with `algorithm`.
