### ISSUE TITLE
Not working with taskSpec ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1159]
is it just me or the dashboard does not work with pipeline runs that declare task spec declared inline ?

**Comment by AlanGreene** [comment]
We should support inline definitions, and we've made some changes to support this in the past for inline Pipeline specs, and inline Task specs.

It's possible we've missed some cases. Can you share an example of one you're expecting to work as well as a screenshot of the behaviour you're seeing?

**Comment by AlanGreene** [comment]
Looks like we're not handling this well, see https://github.com/tektoncd/pipeline/blob/master/examples/v1alpha1/pipelineruns/pipelinerun-with-pipelinespec-and-taskspec.yaml for an example

**Comment by eddycharly** [comment]
Sure,
I am using prow, it is prow so there is some prow syntax here but it shouldn't really matter i guess.
```yaml
buildTaskSpec: &buildTaskSpec
  inputs:
    resources:
      - name: src
        type: git
    params:
      - name: s3path
        type: string
  steps:
    - name: make-build
      image: xxx/php-node-ci
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env bash
        set -e
        make -f tekton.makefile build
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-oauth-token
              key: oauth
      volumeMounts:
        - name: cache-composer
          mountPath: /tmp
      resources:
        requests:
          memory: 1Gi
          cpu: 1
        limits:
          cpu: 1
    - name: make-unit-tests
      image: xxx/php-node-ci
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env bash
        set -e
        make -f tekton.makefile unit-tests
    - name: make-integration-tests
      image: xxx/php-node-ci
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env bash
        set -e
        make -f tekton.makefile integration-tests
    - name: make-package
      image: xxx/php-node-ci
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env bash
        set -e
        make -f tekton.makefile package
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-oauth-token
              key: oauth
      volumeMounts:
        - name: cache-composer
          mountPath: /tmp
    - name: upload-packages
      image: xxx/alpine-utils
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env sh
        set -e
        aws --region eu-central-1 s3 cp package.zip $(inputs.params.s3path) --only-show-errors
  volumes:
    - name: cache-composer
      nfs:
        server: some.nfs.server
        path: /

presubmits:
  - name: pull-ci
    agent: tekton-pipeline
    always_run: true
    skip_report: false
    rerun_command: /run pull-ci
    trigger: "(?m)^/run (all|pull-ci),?(\\s+|$)"
    pipeline_run_spec:
      pipelineSpec:
        params:
          - name: PULL_NUMBER
            type: string
          - name: PULL_PULL_SHA
            type: string
        resources:
          - name: src
            type: git
        tasks:
          - name: build
            taskSpec: *buildTaskSpec
            params:
              - name: s3path
                value: s3://some.s3.bucket/api/pull/$(params.PULL_NUMBER)/$(params.PULL_PULL_SHA)/
            resources:
              inputs:
                - name: src
                  resource: src
      resources:
        - name: src
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
```

When prow runs this pipeline, it apears in the dashboard
![image](https://user-images.githubusercontent.com/47974576/76966598-86d4fb00-6926-11ea-83ad-ad56482afa80.png)

but if i click on it

![image](https://user-images.githubusercontent.com/47974576/76966735-b4ba3f80-6926-11ea-9dde-072907eb966d.png)

The task runs appear correctly under the TaskRuns though.

It could be related to prow but i don't think so, prow simply creates the pipeline run using the tekton client.

Thanks
