### ISSUE TITLE
Show taskRun status where no steps have run and taskRun is running

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#1176]
# Expected behavior

The case where a taskRun has a status but no steps comes up where a taskRun is having problems creating the pod. For example referencing a missing service account.

# Actual behavior

We should feedback these kinds of errors in the pipelineRun view.

# Steps to reproduce the problem

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
  - name: task-one-step-one
    env:
      - name: ENV
        valueFrom:
          configMapKeyRef:
            name: environment-properties
            key: environment
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'echo $ENV']
  - name: task-one-step-two
    image: ubuntu
    command: ['bash']
    args: ['-c', 'echo running'] 
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task2
spec:
  steps:
  - name: task-two-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'echo running'] 
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: 999-working-logs-long
spec:
  tasks:
  - name: task1
    taskRef:
      name: task1
  - name: task2
    taskRef:
      name: task2
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun
spec:
  pipelineRef:
    name: 999-working-logs-long
```

Run the above and click into the pipelineRun view.

# Additional Info
