### ISSUE TITLE
Add rendering for taskRun failure in a pipelineRun where no steps have run

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#1196]
# Expected behavior

Where a pipelineRun fails with no steps there should be feedback on what caused the task to fail

# Actual behavior

Without steps we can't inspect the status of the taskRun

# Steps to reproduce the problem

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
  - name: task-one-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..2}; do echo GONLOGGIN 1 && sleep 1; done;'] 
  - name: task-one-step-two
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..2}; do echo GONLOGGIN 2 && sleep 1; done;'] 
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task2
spec:
  steps:
  - name: task-two-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..2}; do echo GONLOGGIN 1 && sleep 1; done;'] 
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: 999-working-logs-long
spec:
  tasks:
  - name: task1
    taskRef:
      name: task1
  - name: task2
    taskRef:
      name: task2
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: run1
spec:
  pipelineRef:
    name: 999-working-logs-long
  serviceAccountName: 'missingsa'

```
