### ISSUE TITLE
PipelineRuns - Error loading page  Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by serg-bs** [tektoncd/dashboard#1248]
# Expected behavior
   Then run simple pipeline I should see it in PipelineRuns
# Actual behavior
   `Error loading page  Cannot read property 'fn' of undefined`
# Steps to reproduce the problem
**you can reproduce it following step in https://www.katacoda.com/ncskier/scenarios/tekton-dashboard**
or another way
1. Install tekton `kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml`
2. Install dashboard `dashboard kubectl apply --filename https://github.com/tektoncd/dashboard/releases/download/v0.6.0/tekton-dashboard-release.yaml`
3. Create task 
````
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-client
spec:
  steps:
    - name: build-client
      image: ubuntu
      command:
        - /bin/bash
        - -c
      args:
        - echo "Building the client app."
````
4. Create pipeline 
````
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: example-pipeline
spec:
  tasks:
    - name: build-client
      taskRef:
        name: build-client
````
5. Run pipeline
 ````
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: example-pipeline-run
spec:
  pipelineRef:
    name: example-pipeline
````

# Environment
- Kubernetes Platform:
Rancher 2.xx(kubernetes v1.17.4) 

Reproduce only in Chrome browser(unbuntu 18.10),cache in browser was clear. 

In Chrome console 

vendors.187b8556ab88aae32b55.js:93 TypeError: Cannot read property 'fn' of undefined
    at e.select (vendors.187b8556ab88aae32b55.js:48)
    at T (vendors.187b8556ab88aae32b55.js:23)
    at vendors.187b8556ab88aae32b55.js:23
    at e.format (vendors.187b8556ab88aae32b55.js:23)
    at vendors.187b8556ab88aae32b55.js:35
    at Array.map (<anonymous>)
    at p.SY7M.p._formatDurationToParts (vendors.187b8556ab88aae32b55.js:35)
    at p.SY7M.p._formatTokens (vendors.187b8556ab88aae32b55.js:35)
    at vendors.187b8556ab88aae32b55.js:35
    at Array.reduce (<anonymous>)

"TypeError: Cannot read property 'fn' of undefined
    at e.select (http://tekton.goodfin.su/vendors.187b8556ab88aae32b55.js:48:3835075)
    at T (http://tekton.goodfin.su/vendors.187b8556ab88aae32b55.js:23:90727)
    at http://tekton.goodfin.su/vendors.187b8556ab88aae32b55.js:23:93548
    at e.format (http://tekton.goodfin.su/vendors.187b8556ab88aae32b55.js:23:93648)
    at http://tekton.goodfin.su/vendors.187b8556ab88aae32b55.js:35:86128
    at Array.map (<anonymous>)
    at p.SY7M.p._formatDurationToParts (http://tekton.goodfin.su/vendors.187b8556ab88aae32b55.js:35:85945)
    at p.SY7M.p._formatTokens (http://tekton.goodfin.su/vendors.187b8556ab88aae32b55.js:35:85810)
    at http://tekton.goodfin.su/vendors.187b8556ab88aae32b55.js:35:85148
    at Array.reduce (<anonymous>)"

Then I open PipelineRuns In firefox I see same error, but only few millisecond. Then open PipelineRuns correct.
