### ISSUE TITLE
Deeplink does not work after auth redirect due to the use of URL fragment based routing

### ISSUE THREAD

**Issue by jieyu** [tektoncd/dashboard#1360]
We put tekton dashboards behind a reverse proxy that performs OIDC based authentication flow. When a new user clicks a link to a pipeline run from the github commit status (e.g., `https://<cluster_url>/tekton/#/namespaces/default/pipelineruns/xxx`), the proxy will perform OIDC login flow. Once the OIDC login finishes and succeeds, the browser will redirected to the original URL. However, after the auth redirection, the fragment part of the original deeplink is dropped (i.e., `https://<cluster_url>/tekton/`). Thus, the users will always be routed to the main page, not the specific pipelinerun view.

# Expected behavior

After auth redirection, the user should be taken to the pipelinerun view

# Actual behavior

After auth redirection, the user always sees the main page

# Steps to reproduce the problem

Put dashboard behind a reverse proxy (e.g. envoy) that perform OIDC login flow for authentication.

# Environment
- Kubernetes Platform: Kubernetes 1.16.8

- Tekton Pipelines version: v0.11.1

- Tekton Triggers version:

- Tekton Dashboard version: 0.6.1

# Additional Info

Using latest chrome

**Comment by AlanGreene** [comment]
Which browser(s) are you seeing this behaviour in? I've seen problems in some browsers in the past not properly preserving the fragment on redirects, depending on number or redirects, number of domains involved, etc.

@a-roberts have you seen anything like this with the oauth-proxy on OpenShift?

---

Some background on the use of URL fragment for our routing... There are a number of reasons we use fragment based routing instead of path based, including the fact that we can't reliably determine the root path for the dashboard since the same deployment could be accessed in a number of different ways:
- `kubectl proxy` e.g. `localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/`
- `kubectl port-forward` e.g. `localhost:9097/`
- using an ingress / route with optional path e.g. `<cluster_url>/tekton`
- ...

Using the URL fragment provides a reliable mechanism to support client side routing in all of these scenarios.

**Comment by jieyu** [comment]
@AlanGreene I am using chrome

**Comment by AlanGreene** [comment]
Can you reproduce this using another application (even just a simple http server with a static page) behind your OIDC proxy in place of the dashboard? This would help to narrow down where the cause lies.

I suspect one of the redirects in your login flow includes its own fragment (including state, token, or similar) which would override the original fragment on the target URL, but it would be good to confirm this so we can understand the issue and determine what options might be available.

**Comment by jieyu** [comment]
I launched a simple nginx server behind the proxy (Ingress) and put it under `/nginx`. And then, I typed the following URL in the browser:
```
https://<cluster_url>/nginx/#foobar
```
Once the redirect finishes, i can see that the `#foobar` part is dropped
```
https://<cluster_url>/nginx/
```

I'll try to see if I can reproduce using a different oidc proxy

**Comment by jieyu** [comment]
xref: https://github.com/elastic/kibana/issues/18392#issuecomment-384120359

I think this issue in kibana is related to this problem

**Comment by a-roberts** [comment]
> 
> @a-roberts have you seen anything like this with the oauth-proxy on OpenShift?
> 

No, we've been testing as we go on OpenShift, including with the pull request monitor task for the webhooks extension, since OpenShift 3.11 and we include a PipelineRun link in the comment that works 🤔

**Comment by jieyu** [comment]
@a-roberts so the link works with unauthenticated users (meaning it requires a full oidc connect login flow)?

**Comment by jieyu** [comment]
I was able to reproduce this using another proxy (ambassador's oauth2 integration) with auth0 as IDP. Here are the steps:

* Launch a kubernetes cluster (we're using 1.16.8) on AWS
* Install ambassador ingress
```bash
$ helm install --name ambassador --namespace ambassador datawire/ambassador
```
* Integrate ambassador with auth0. You can following this tutorial here: https://www.getambassador.io/docs/latest/howtos/sso/auth0/

```yaml
---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: auth-filter
  namespace: ambassador
spec:
  OAuth2:
    authorizationURL: https://jie.auth0.com
    extraAuthorizationParameters:
      audience: https://jie.auth0.com/api/v2/
    clientID: 6Qj7QeKPH7jPZs5K6AmrlHXzSVAY0STb
    secret: SOME_SECRET_HERE
    protectedOrigins:
    - origin: https://ae7723ac3d24841f6872adc4085d31b2-664452685.us-west-2.elb.amazonaws.com
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: auth-filter-policy
  namespace: ambassador
spec:
  rules:
  - host: ae7723ac3d24841f6872adc4085d31b2-664452685.us-west-2.elb.amazonaws.com
    path: /
    filters:
    - name: auth-filter
      arguments:
        scopes:
        - "openid"
```
* Install an ingress for the tekton dashboard like the following (assuming it's already installed)
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: ambassador
  name: tekton-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tekton-dashboard
          servicePort: 9097
        path: /
```
* Then, use a deep link to access a particular page. It'll trigger oidc login flow. After login, the URL fragment is lost
