### ISSUE TITLE
dashboard requires secrets access in all namespaces 

### ISSUE THREAD

**Issue by dghubble** [tektoncd/dashboard#1386]
Run dashboard with `READ_ONLY` true and a Tekton pipelines scoped to a single namespace. The aim of this usage style is that `dashboard` should provide a read-only view of `Tasks`, `TaskRuns`, `Pipelines`, and `PipelineRuns` (that reside in a single namespace) and view those pod logs. Nothing more.

# Expected behavior

Dashboard (read-only) should not require access to secrets, service accounts, deployments, services, ingress, or configmaps. Be able to run dashboard without access to these resources:

- [ ] secrets ()
- [ ] [service accounts](https://github.com/tektoncd/dashboard/blob/57082bcc24df0f24c248685bbe31bb38f9c8cda1/base/200-clusterrole.yaml#L38)
- [x] [deployments](https://github.com/tektoncd/dashboard/blob/57082bcc24df0f24c248685bbe31bb38f9c8cda1/base/200-clusterrole.yaml#L50) (runs ok without access)
- [ ] [services](https://github.com/tektoncd/dashboard/blob/57082bcc24df0f24c248685bbe31bb38f9c8cda1/base/200-clusterrole.yaml#L41) 
- [x] [configmaps](https://github.com/tektoncd/dashboard/blob/57082bcc24df0f24c248685bbe31bb38f9c8cda1/base/200-clusterrole.yaml#L47) (runs ok without access)
- [x] [ingress](https://github.com/tektoncd/dashboard/blob/57082bcc24df0f24c248685bbe31bb38f9c8cda1/base/200-clusterrole.yaml#L35) (runs ok without access)

I think cluster-level list/watch namespaces is ok since th UI provides a namespace picker (we'd always just pick the single namespace we care about, that's ok)

# Actual behavior

Dashboard logs show it tries to access secrets, service accounts, and services (without backoff too btw).

```
E0517 20:56:26.610318       1 reflector.go:123] runtime/asm_amd64.s:1357: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:tekton:tekton-dashboard" cannot list resource "services" in API group "" at the cluster scope
E0517 20:56:26.897287       1 reflector.go:123] runtime/asm_amd64.s:1357: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:tekton:tekton-dashboard" cannot list resource "secrets" in API group "" at the cluster scope
E0517 20:56:27.567116       1 reflector.go:123] runtime/asm_amd64.s:1357: Failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:tekton:tekton-dashboard" cannot list resource "serviceaccounts" in API group "" at the cluster scope
```

These are not authorizations we can allow. Cluster-wide secrets read is effectively cluster-wide admin, something we can't dole out, especially not to an application that's user/network facing. The other items, dashboard should not need to access.

# Steps to reproduce the problem

Run dashboard with a stripped down ClusterRole.

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-dashboard
rules:
  # UI namespaces picker
  - apiGroups:
    - ""
    resources:
      - namespaces
    verbs:
      - list
      - watch
  # Tekton cluster-scoped CRDs
  - apiGroups:
      - tekton.dev
    resources:
      - clustertasks
      - clustertasks/status
    verbs:
      - get
      - list
      - watch
  # TODO: These should actually be a Role (single namespace scope)
  # Tekton Pipeline CRDs
  - apiGroups:
    - tekton.dev
    resources:
    - tasks
    - taskruns
    - taskruns/finalizers
    - pipelines
    - pipelineruns
    - pipelineruns/finalizers
    - pipelineresources
    - conditions
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - tekton.dev
    resources:
    - tasks/status
    - taskruns/status
    - pipelines/status
    - pipelineruns/status
    - pipelineresources/status
    verbs:
    - get
```

And a Role for the namespace where Task/Pipeline pods are run.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-dashboard
  namespace: tekton
rules:
  # Tekton Triggers CRDs
  - apiGroups:
    - triggers.tekton.dev
    resources:
    - eventlisteners
    - triggerbindings
    - triggertemplates
    verbs:
    - get
  # Pod logs
  - apiGroups:
    - ""
    resources:
    - pods/log
    verbs:
    - get
    - list
    - watch
```

We're able to use the dashboard well enough to view Tasks and TaskRuns and pod logs in the single namespace we care about. For now, I deny dashboard any other permissions and ignore logs. 

# Environment

- Kubernetes Platform:Typhoon
- Tekton Pipelines version: v0.12.0
- Tekton Triggers version: v0.5.0
- Tekton Dashboard version: v0.6.1.3

# Additional Info

Related work in-flight:

* https://github.com/tektoncd/dashboard/pull/1371
* https://github.com/tektoncd/dashboard/pull/1378
