### ISSUE TITLE
TaskRun Failure shows invalid steps status for pipelineResource image error

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#1451]
# Expected behavior

The first step ran and should not show `not run` as its status

# Actual behavior

![Screenshot 2020-05-29 at 11 42 51](https://user-images.githubusercontent.com/18128367/83251572-b2cff080-a1a1-11ea-9c8b-0358c66f47bc.png)

# Steps to reproduce the problem

Sample resources 

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-to-build
spec:
  type: image
  params:
  - name: url
    value: ubuntu
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  resources:
    outputs:
    - name: built-image
      type: image
      description: (Optional) The image to build
      optional: true
  steps:
  - name: task-one-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 1 && sleep 3; done;'] # tests that targetpath works
  - name: task-one-step-two
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 2 && sleep 3; done;'] 
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task2
spec:
  resources:
    outputs:
    - name: built-image
      type: image
      description: (Optional) The image to build
      optional: true
  results:
  - name: image-tags
    description: the tags for the built image
  - name: image-digest
    description: the image digest (sha-256 hash) for the built image
  steps:
  - name: task-two-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 1 && sleep 3; done; && fail'] # tests that targetpath works
  - name: task2step-two
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 2 && sleep 3; done;'] 
  - name: task-two-tep-three
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 1 && sleep 3; done;'] # tests that targetpath works
  - name: task-two-step-four
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 2 && sleep 3; done;'] 
---
#The Output of the first Task (git resource) create-file is given as an `Input`
# to the next `Task` check-stuff-file-exists using`from` clause.

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: 999-working-logs-long
spec:
  resources:
  - name: app-image
    type: image
  tasks:
  - name: task1
    taskRef:
      name: task1
  - name: task2
    runAfter: [task1]
    taskRef:
      name: task2
    resources:
      outputs:
      - name: built-image
        resource: app-image
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: gone-runnin-99932312
spec:
  timeout: 30m
  pipelineRef:
    name: 999-working-logs-long
  resources:
  - name: app-image
    resourceRef:
      name: image-to-build
```

@AlanGreene FYI
