### ISSUE TITLE
Dashboard unaccessible on OpenShift after replacing the default ingress certificate

### ISSUE THREAD

**Issue by JustinKuli** [tektoncd/dashboard#1603]
# Describe the bug

We get a `500 Internal Error` page when trying to access the Tekton dashboard in our OpenShift cluster. We recently replaced the default ingress certificate in our cluster according to this procedure: https://docs.openshift.com/container-platform/4.3/authentication/certificates/replacing-default-ingress-certificate.html

Logs from the `oauth-proxy` container show:
```
2020/07/07 11:12:13 oauthproxy.go:645: error redeeming code (client: [ IP address elided ]): Post https://oauth-openshift.apps.[ url elided ]/oauth/token: x509: certificate signed by unknown authority
2020/07/07 11:12:13 oauthproxy.go:438: ErrorPage 500 Internal Error Internal Error
```

# Expected behaviour

We expected that the dashboard would automatically trust the custom certificate we configured the cluster with.

# Steps to reproduce the bug

Configure oauth in your cluster, then change the default ingress certificate for OpenShift.

# Environment details

- Kubernetes Platform: OpenShift 4.3

- Kubernetes or OpenShift version: v1.16.2

- Install mode (if on OpenShift): non-operator

- Cloud-provider/provisioner:

- Versions:
   - Tekton Dashboard: 0.5.2
   
   - Tekton Pipelines: 0.10.1
   
   - Tekton Triggers:
   
- Install namespaces:
   - Tekton Dashboard: tekton-pipelines
   
   - Tekton Pipelines: openshift-pipelines
   
   - Tekton Triggers:
   

# Additional Info

**Comment by JustinKuli** [comment]
This issue seems the most similar: https://github.com/openshift/oauth-proxy/issues/73, but it doesn't have a full explanation of resolving the issue. The issue here is that the OpenShift oauth server is at a `*.apps.` address which has had its certificate changed, and the oauth-proxy container does not trust something in the certificate authority chain.

There is an `--openshift-ca` argument for the oauth-proxy container which seems like it can resolve this problem. Since the OpenShift cluster already has information about the new CA (per the procedure at https://docs.openshift.com/container-platform/4.3/authentication/certificates/replacing-default-ingress-certificate.html), we just need to get that certificate into the container and use it.

This page has details on how we can get the new certificate (in a bundle) into a configmap in the namespace: https://docs.openshift.com/container-platform/4.3/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki, and then we can apply a patch to the deployment configuration to connect everything.

# Workaround

1. Create an empty configmap with this yaml, it will then be populated by OpenShift with the certificate bundle:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: ocp-ca-bundle
  namespace: tekton-pipelines
```

2. Create this patch-file.yaml file for the deployment:
```
spec:
  template:
    spec:
      containers:
        - name: oauth-proxy
          args:
            - --https-address=:8443
            - --provider=openshift
            - --skip-provider-button=true
            - --openshift-service-account=tekton-dashboard
            - --upstream=http://localhost:9097
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret=SECRET
            - --skip-auth-regex=^/v1/extensions/.*\.js
            - --openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --openshift-ca=/etc/ocp-injected-certs/tls-ca-bundle.pem
          volumeMounts:
            - mountPath: /etc/ocp-injected-certs
              name: ocp-injected-certs
      volumes:
        - name: ocp-injected-certs
          configMap:
            name: openshift-cabundle
            defaultMode: 420
            items:
            - key: ca-bundle.crt
              path: tls-ca-bundle.pem
```

3. Apply the patch:
```
oc -n tekton-pipelines patch deployment tekton-dashboard --patch "$(cat patch-file.yaml)" 
```
