### ISSUE TITLE
Event listeners detail page, Error loading page  Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by hb-chen** [tektoncd/dashboard#1954]
# Describe the bug

http://{host}/#/namespaces/default/eventlisteners/xxx
event listeners detail page get this error

# Expected behaviour
 
no error

# Steps to reproduce the bug

# Environment details

- Kubernetes Platform:
  - Rancher
- Kubernetes or OpenShift version:
  - v1.19.7
- Versions:
  - Tekton Dashboard:
    - v0.14.0
  - Tekton Pipelines:
    - v0.20.0
  - Tekton Triggers:
    - v0.10.2
- Install namespaces:
  - Tekton Dashboard:
    - tekton-pipelines
  - Tekton Pipelines:
    - tekton-pipelines
  - Tekton Triggers:
    - tekton-pipelines
  - event-listeners
    - default
# Additional Info

```
main.50fc6cd….js:1 ErrorBoundary 
{error: TypeError: Cannot read property 'join' of undefined
    at http://{host}/main.50fc6c…, info: {…}}
error: TypeError: Cannot read property 'join' of undefined at http://{host}/main.50fc6cd8cf37d9864f90.js:1:469042 at Array.map (<anonymous>) at http://{host}/main.50fc6cd8cf37d9864f90.js:1:467535 at ra (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1248039) at Vl (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1300244) at Ss (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1287451) at Os (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1287379) at xs (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1287242) at ds (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1284229) at http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1233937
message: "Cannot read property 'join' of undefined"
stack: "TypeError: Cannot read property 'join' of undefined↵    at http://{host}/main.50fc6cd8cf37d9864f90.js:1:469042↵    at Array.map (<anonymous>)↵    at http://{host}/main.50fc6cd8cf37d9864f90.js:1:467535↵    at ra (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1248039)↵    at Vl (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1300244)↵    at Ss (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1287451)↵    at Os (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1287379)↵    at xs (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1287242)↵    at ds (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1284229)↵    at http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1233937"
__proto__: Error
info:
componentStack: "↵    at http://{host}/main.50fc6cd8cf37d9864f90.js:1:465614↵    at injectIntl(Component)↵    at div↵    at div↵    at div↵    at div↵    at u (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:253504)↵    at c (http://{host}/main.50fc6cd8cf37d9864f90.js:1:455878)↵    at u (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:256411)↵    at i (http://{host}/main.50fc6cd8cf37d9864f90.js:1:455945)↵    at div↵    at M (http://{host}/main.50fc6cd8cf37d9864f90.js:1:440209)↵    at injectIntl(M)↵    at EventListenerContainer (http://{host}/main.50fc6cd8cf37d9864f90.js:1:173802)↵    at injectIntl(EventListenerContainer)↵    at E (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1332881)↵    at t (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1347815)↵    at t (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1349798)↵    at i (http://{host}/main.50fc6cd8cf37d9864f90.js:1:416826)↵    at injectIntl(i)↵    at http://{host}/main.50fc6cd8cf37d9864f90.js:1:429714↵    at injectIntl(Component)↵    at withRouter(injectIntl(Component)) (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1350335)↵    at main↵    at d (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:283393)↵    at t (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1344489)↵    at t (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1339960)↵    at IntlProvider (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1323858)↵    at App (http://{host}/main.50fc6cd8cf37d9864f90.js:1:63750)↵    at E (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1332881)↵    at c (http://{host}/vendors.b86ad2fbb0a36bcc3697.js:2:1330815)"
__proto__: Object
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
```

**Comment by AlanGreene** [comment]
Thanks for reporting. Can you share details of the EventListener you're seeing this with? Either a copy of the resource or a description of the fields you're using would be very helpful.

**Comment by hb-chen** [comment]
This is my el, binding and template yaml. Used github interceptor.
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "123456"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor
spec:
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
      bindings:
        - ref: pipeline-binding
      template:
        ref: grpc-gateway-pipeline-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-example-sa
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: grpc-gateway-pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: grpc-gateway-pipeline-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: grpc-gateway-pipeline
        workspaces:
          - name: shared-workspace
            persistentvolumeclaim:
              claimName: golang-source-pvc
        params:
          - name: url
            value: $(tt.params.gitrepositoryurl)
          - name: revision
            value: $(tt.params.gitrevision)

```
