### ISSUE TITLE
Port-forwarding works, but the ingress does not work for dashboard

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/dashboard#2017]
# Describe the bug

I am using the kubernetes service on dosker-desktop locally.
I install the dashboard with the command `kubectl apply -f https://github.com/tektoncd/dashboard/releases/download/v0.16.1/tekton-dashboard-release.yaml`

I install the nginx with `kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.45.0/deploy/static/provider/cloud/deploy.yaml`.  The nginx worked fine with other services, but not the dashboard.

The ingress looks like:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /dashboard
            pathType: Prefix
            backend:
              service:
                name: tekton-dashboard
                port:
                  number: 9097
```

# Expected behaviour

I should be able to access the dashboard page at http://localhost/dashboard/, but it showed `404 page not found`.

# Steps to reproduce the bug

# Environment details

- Kubernetes Platform:
docker desktop
- Versions:
   - Tekton Dashboard: 0.16.1
- Install namespaces:
   - Tekton Dashboard: tekton-pipelines

# Additional Info

**Comment by houshengbo** [comment]
Problem solved. We have to be aware the `escape` before $2 and $1, when saving the content into yaml files.
It works differently with the `cat` command.

**Comment by kuznero** [comment]
@houshengbo, can you please provide a working example of an ingress?

**Comment by kuznero** [comment]
When ingress looks like this, it does not seem to work:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: tekton-dashboard
                port:
                  number: 9097
            path: /tekton/dashboard(/|$)(.*)
            pathType: Prefix
```

One difference though with the original setup above is that I am accessing it on the port - `localhost:7080/tekton/dashboard`.
