### ISSUE TITLE
Websocket not work when I used ELB, ALB or NLB (AWS)

### ISSUE THREAD

**Issue by alanmoment** [tektoncd/dashboard#2068]
tekton-dashboard v.0.17.0

The websocket is work when I used port-forward. But other scenario not work.

**first scenario**

I setup ingress-nginx to visit dashboard. But I can't auto reload from websocket when I do something action.

PS: auto create ELB

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-dashboard-ro
  namespace: tekton-pipelines
  labels:
    app: tekton-dashboard-ro
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/name: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-dashboard-ro
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "tekton-dashboard-ro.xxx.xxx"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: tekton-dashboard-ro
              port:
                number: 9097
```

I got error from console

```
GET wss://tekton-dashboard-ro.xxx.xxx/v1/websockets/resources
[HTTP/1.1 400 Bad Request 161ms]

Firefox can’t establish a connection to the server at wss://tekton-dashboard-ro.xxx.xxx/v1/websockets/resources.
``` 

**second scenario**

I also try to use ALB and NLB. But I got 502 error code when I goto dashboard. By the way. health check is fine.

PS: delete Ingress and service change to nodePort

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-dashboard-ro
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: dashboard
    app.kubernetes.io/part-of: tekton-dashboard-ro
    app.kubernetes.io/version: v0.17.0
    dashboard.tekton.dev/release: v0.17.0
    version: v0.17.0
  name: tekton-dashboard-ro
  namespace: tekton-pipelines
spec:
  ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 9097
      nodePort: 30097
  type: NodePort
  selector:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: dashboard
    app.kubernetes.io/part-of: tekton-dashboard-ro
```

# Expected behaviour

Auto reload from websocket when I setup ingress-nginx, ALB or NLB

# Environment details

- Kubernetes Platform: v1.19.9
- Cloud-provider/provisioner: kOps on AWS
- Versions:
   - Tekton Dashboard: v0.17.0
   - Tekton Pipelines: v0.23.0
   - Tekton Triggers: v0.13.0
- Install namespaces:
   - Tekton Dashboard: tekton-pipelines
   - Tekton Pipelines: tekton-pipelines
   - Tekton Triggers: tekton-pipelines

**Comment by AlanGreene** [comment]
Hey @alanmoment, thanks for reporting the issue. We have the same Tekton versions currently deployed to our [dogfooding cluster](https://dashboard.dogfooding.tekton.dev/#/about) on GKE with the Dashboard exposed via [ingress](https://github.com/tektoncd/plumbing/blob/bcb46a7a1a51d4be74cb887ace1421466be696ae/tekton/cd/dashboard/overlays/dogfooding/ingress.yaml). Websockets are working as expected there so it's likely the issue is in either your loadbalancer or ingress config.

How is your ingress controller exposed? From the [ingress-nginx docs](https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#websockets) it notes:

> If the NGINX ingress controller is exposed with a service `type=LoadBalancer` make sure the protocol between the loadbalancer and NGINX is TCP.

**Comment by alanmoment** [comment]
Thank you to reply. Below is ingress-nginx setting:

```
controller:
  service:
    enableHttp: false
    enableHttps: true
    targetPorts:
      http: http
      https: http
    annotations:
      external-dns.alpha.kubernetes.io/hostname:
        "tekton-dashboard-ro.xxx.xxx"
      service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "xxxx"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
```

Could you please give me some advice?
