### ISSUE TITLE
Add support for display details of `PipelineRun` which uses `Pipeline` from Tekton Bundle

### ISSUE THREAD

**Issue by mdreizin** [tektoncd/dashboard#2087]
# Describe the bug

Dashboard does not display any details of `PipelineRun` which uses `Pipeline` from Tekton Bundle:

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: my-pipeline-1
spec:
  pipelineRef:
    name: my-pipeline
    bundle: grc.io/my-catalog/my-pipeline:0.1
  params: []
```

# Expected behaviour

It would be nice to display details of such `PipelineRun`-s.

# Steps to reproduce the bug

1. Publish `Pipeline` as Tekton Bundle
2. Create a simple `PipelineRun` which will use `Pipeline` from that bundle.

# Environment details

- Kubernetes Platform: GCP

- Kubernetes or OpenShift version: 

- Install mode (if on OpenShift): -

- Cloud-provider/provisioner: GKE

- Versions:
   - Tekton Dashboard: 0.17.0
   
   - Tekton Pipelines: 0.24.1
   
   - Tekton Triggers: 0.14.1
   
- Install namespaces:
   - Tekton Dashboard: tekton-pipelines
   
   - Tekton Pipelines: tekton-pipelines
   
   - Tekton Triggers: tekton-pipelines
   

# Additional Info

A simple workaround is to publish a pipeline by `kubectl` to display missing details.
