### ISSUE TITLE
Add possibility to specify workspace when creating a pipeline

### ISSUE THREAD

**Issue by t0mdev** [tektoncd/dashboard#2109]
# Is your feature request related to a problem ?

We have a pipeline, which uses workspaces to allow sharing our git repository between tasks.

We would like to manually trigger this pipeline via the tekton dashboard. However, this is not possible via the /pipelineruns/create UI, because there I cannot specify a volume or volume claim.

# Describe the solution you'd like

Add the possibility to specify a workspace and volume claim in the /pipelineruns/create UI.

# Describe alternatives you've considered

Our workaround is, to have a task that creates a pipeline run via kubectl apply. Similar to the example below, this pipeline run contain a volume claim definition. This task can be triggered via /taskruns/create UI.

# Additional context

The PipelineRun spec should allow this, see the example below. As far as I can see, only the possibility to configure it in the UI is missing.
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
spec:
  pipelineRef:
    name: our-pipeline
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 3000Mi
          volumeMode: Filesystem
          accessModes:
            - ReadWriteOnce
 ```
