### ISSUE TITLE
Readonly dashboard still has delete button

### ISSUE THREAD

**Issue by rouke-broersma** [tektoncd/dashboard#2128]
# Describe the bug

When we deploy the tekton dashboard as readonly, TaskRuns have a delete button when you select one or more items. This delete button actually deletes the TaskRuns.

# Expected behaviour

In readonly mode nothing should be modifyable using the dashboard.

# Environment details

<html>
<body>
<div class="tkn--table" id="tkn--about--dashboard-table" style="box-sizing: border-box; padding: 0px; border: 0px; margin: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: &quot;IBM Plex Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(22, 22, 22); letter-spacing: 0.16px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 244, 244); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="bx--data-table-container" style="box-sizing: border-box; padding-top: var(--cds-spacing-01, 0.125rem); padding-right: 0px; padding-bottom: 0px; padding-left: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline; width: 1336px;"><div class="bx--data-table-header" style="box-sizing: border-box; padding-top: ; padding-right: ; padding-bottom: var(--cds-spacing-03, 0.5rem); padding-left: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline; background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat-x: ; background-repeat-y: ; background-attachment: ; background-origin: ; background-clip: ; background-color: transparent !important;"><h4 class="bx--data-table-header__title" style="box-sizing: border-box; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--cds-productive-heading-03-font-weight, 400); font-stretch: inherit; line-height: var(--cds-productive-heading-03-line-height, 1.4); font-family: inherit; font-size: var(--cds-productive-heading-03-font-size, 1.25rem); vertical-align: baseline; letter-spacing: var(--cds-productive-heading-03-letter-spacing, 0); color: var(--cds-text-primary, #161616);">Dashboard</h4><p class="bx--data-table-header__description" style="box-sizing: border-box; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--cds-body-short-01-font-weight, 400); font-stretch: inherit; line-height: var(--cds-body-short-01-line-height, 1.29); font-family: inherit; font-size: var(--cds-body-short-01-font-size, 0.875rem); vertical-align: baseline; letter-spacing: var(--cds-body-short-01-letter-spacing, 0.16px); color: var(--cds-text-secondary, #525252);"></p></div><div class="bx--data-table-content" style="box-sizing: border-box; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline; overflow-x: auto;">

Property | Value
-- | --
Namespace | tekton-pipelines
Version | v0.18.0
ReadOnly | True

</div></div></div>
</body>
</html>

<html>
<body>
<div class="bx--data-table-header" style="box-sizing: border-box; padding-top: ; padding-right: ; padding-bottom: var(--cds-spacing-03, 0.5rem); padding-left: 0px; border: 0px; margin: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: &quot;IBM Plex Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; vertical-align: baseline; background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat-x: ; background-repeat-y: ; background-attachment: ; background-origin: ; background-clip: ; background-color: rgb(244, 244, 244); color: rgb(22, 22, 22); letter-spacing: 0.16px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h4 class="bx--data-table-header__title" style="box-sizing: border-box; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--cds-productive-heading-03-font-weight, 400); font-stretch: inherit; line-height: var(--cds-productive-heading-03-line-height, 1.4); font-family: inherit; font-size: var(--cds-productive-heading-03-font-size, 1.25rem); vertical-align: baseline; letter-spacing: var(--cds-productive-heading-03-letter-spacing, 0); color: var(--cds-text-primary, #161616);">Pipelines</h4><p class="bx--data-table-header__description" style="box-sizing: border-box; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--cds-body-short-01-font-weight, 400); font-stretch: inherit; line-height: var(--cds-body-short-01-line-height, 1.29); font-family: inherit; font-size: var(--cds-body-short-01-font-size, 0.875rem); vertical-align: baseline; letter-spacing: var(--cds-body-short-01-letter-spacing, 0.16px); color: var(--cds-text-secondary, #525252);"></p></div><div class="bx--data-table-content" style="box-sizing: border-box; padding: 0px; border: 0px; margin: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: &quot;IBM Plex Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; vertical-align: baseline; overflow-x: auto; color: rgb(22, 22, 22); letter-spacing: 0.16px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 244, 244); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Property | Value
-- | --
Namespace | tekton-pipelines
Version | v0.25.0

</div>
</body>
</html>

![image](https://user-images.githubusercontent.com/3595932/125581114-4cdc6059-1d2a-46f4-8053-3514e9bde6bd.png)

**Comment by AlanGreene** [comment]
Thanks for reporting @rouke-broersma. I do see the checkboxes on TaskRuns and have identified the bug but it looks like a purely UI issue. When I attempt to delete the TaskRuns it is blocked as expected due to missing permissions, e.g.:

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"taskruns.tekton.dev \"log-test-d69l9-r-b4xdp\" is forbidden: User \"system:serviceaccount:tekton-pipelines:tekton-dashboard\" cannot delete resource \"taskruns\" in API group \"tekton.dev\" in the namespace \"test\"","reason":"Forbidden","details":{"name":"log-test-d69l9-r-b4xdp","group":"tekton.dev","kind":"taskruns"},"code":403} (error code 403)
```

Can you confirm that the TaskRuns are actually deleted when you click the button?

What Kubernetes platform are you running this on? e.g. Docker Desktop, GKE, OpenShift, etc.

On Docker Desktop for example, Kubernetes RBAC rules are not enforced by default, all service accounts are essentially granted cluster admin role so regardless of what rules we configure for the Dashboard in that environment all actions are permitted. Most other platforms do enforce RBAC by default so it should be blocked as expected.

I'll create a fix for the checkboxes showing up when they shouldn't and we'll get a patch release out ASAP.

**Comment by rouke-broersma** [comment]
We are running on AKS and I can confirm that the delete action actually deletes the taskruns.

**Comment by AlanGreene** [comment]
Can you verify the contents of the `tekton-dashboard-tenant` ClusterRole, for TaskRuns it should only have `get`, `list`, and `watch` enabled.

```yaml
- apiGroups:
  - tekton.dev
  resources:
  …
  - taskruns
  …
  verbs:
  - get
  - list
  - watch
```

How did you install the Dashboard? Was it a fresh install or an update to a previous install? If updating a previous install, was that also in read-only mode?

**Comment by rouke-broersma** [comment]
If I'm understanding the ClusterRole correctly this is the relevant part of our manifest:

```yaml
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - taskruns
      - pipelines
      - pipelineruns
      - pipelineresources
      - conditions
      - tasks/status
      - taskruns/status
      - pipelines/status
      - pipelineruns/status
      - taskruns/finalizers
      - pipelineruns/finalizers
    verbs:
      - get
      - list
      - watch
```

The dashboard manifest was updated from:

```yaml
spec:
      containers:
        - args:
            - --port=9097
            - --logout-url=
            - --pipelines-namespace=tekton-pipelines
            - --triggers-namespace=tekton-pipelines
            - --read-only=false
            - --log-level=info
            - --log-format=json
            - --namespace=
            - --stream-logs=false
            - --external-logs=
```

To:

```yaml
spec:
      containers:
        - args:
            - --port=9097
            - --logout-url=
            - --pipelines-namespace=tekton-pipelines
            - --triggers-namespace=tekton-pipelines
            - --read-only=true
            - --log-level=info
            - --log-format=json
            - --namespace=
            - --stream-logs=false
            - --external-logs=
```

And also from v0.17.0 to v0.18.0 at the same time.
