### ISSUE TITLE
Cannot set property 'source' of undefined

### ISSUE THREAD

**Issue by Adiqq** [tektoncd/dashboard#2181]
# Describe the bug
Error message in `#/taskruns/create`  page after selecting `Input PipelineResources` of type `git`. It's possible to re-run this `TaskRun` from Dashboard, but it's not possible to create new `TaskRun` from this `Task` using Dashboard
```
Error loading page

Cannot set property 'source' of undefined
```

# Expected behaviour

No error message, if some element cannot be handled properly, it should be possible at least to select by name without crashing page. 

# Steps to reproduce the bug

Apply below definitions:
```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-deploy-git
  namespace: app
spec:
  type: git
  params:
    - name: url
      value: git@gitlab.com:app/app-deploy.git 
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl
  namespace: app
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
  steps:
    - name: view-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "kustomize"
        - "$(inputs.resources.source.path)/$(inputs.params.pathToYamlFile)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-k"
        - "$(inputs.resources.source.path)/$(inputs.params.pathToYamlFile)"
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-using-kubectl-staging
  namespace: app
spec:
  params:
    - name: pathToYamlFile
      value: overlay/staging
  resources:
    inputs:
      - name: source
        resourceRef:
          name: app-deploy-git
  serviceAccountName: app
  taskRef:
    name: deploy-using-kubectl
---
```

Go to `$TEKTON_URL/#/taskruns/create`

Select task `deploy-using-kubectl`

Select `Input PipelineResources` of type `git` named `source`

# Environment details

- Kubernetes Platform:
k3s
- Kubernetes or OpenShift version:
v1.21.3
- Versions:
   - Tekton Dashboard:
latest
`gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:81c6e5343eba03333b3bc7bbee2977090daf559d550ae22e570b9d1e1e52c471`
   - Tekton Pipelines:
v.0.27.2
`gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.27.2@sha256:3e01856d4d83787c702c949b6ef7e9319ec5b96cdd9a60a0967fa1986657cef9`
   - Tekton Triggers:
v.0.15.1
`gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.15.1@sha256:8a1a584fdaf0d29c6229f704947fbf5d46c0d0aa18d056bb040cdc5f66c99e54`
- Install namespaces:
   - Tekton Dashboard:
   tekton-pipelines
   - Tekton Pipelines:
   tekton-pipelines
   - Tekton Triggers:
   tekton-pipelines

# Additional Info
