### ISSUE TITLE
Upgrade from 0.18.0 to 0.19.0 results in API errors

### ISSUE THREAD

**Issue by cameronbraid** [tektoncd/dashboard#2183]
kubernetes v1.21.1

I had a working dashboard v0.18.0, after upgrading to 0.19.0 I get the following error :

```
Error loading PipelineRuns

{"stack":"Error\n at m (https://.../main.94eb5a1454792e07c003.js:1:6770)\n at https://.../main.94eb5a1454792e07c003.js:1:6916","message":"","response":{}}
```

And an example error in network dev tools 

https://.../proxy/apis/tekton.dev/v1beta1/pipelineruns/

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "pipelineruns.tekton.dev is forbidden: User \"system:anonymous\" cannot list resource \"pipelineruns\" in API group \"tekton.dev\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "group": "tekton.dev",
    "kind": "pipelineruns"
  },
  "code": 403
}
```

**Comment by AlanGreene** [comment]
How did you upgrade to v0.19.0?

Can you compare the role(binding)s applied on your cluster with those defined in the Dashboard release manifest?

Permission to list PipelineRuns is granted in the ClusterRole `tekton-dashboard-tenant`.

**Comment by AlanGreene** [comment]
Closing.  If you're still seeing this feel free to reopen with additional info to help reproduce and debug the issue.

**Comment by cameronbraid** [comment]
I cant see a way to re-open.

Additional information :

* the manifests are the same
* I deploy using html template to file then kapp apply to deploy
* I also verified by fully removing the previous version before installing the new version rather than doing an upgrade and still have the same issue

**Comment by cameronbraid** [comment]
fyI the yaml diff when upgrading from v0.18 to v0.20 for the clusterrole is :
```
@@ update clusterrole/tekton-dashboard-tenant (rbac.authorization.k8s.io/v1) cluster @@
  ...
 53, 53     resources:
 54     -   - serviceaccounts
 55     -   - pods/log
     54 +   - events
 56, 55     - namespaces
     56 +   - pods
     57 +   - pods/log
     58 +   - serviceaccounts
 57, 59     verbs:
 58, 60     - get
  ...
122,124     - patch
123     -   - add
124,125   
```

**Comment by cameronbraid** [comment]
I think I have found the issue.  I run istio and have an EnvoyFilter configured for authentication :

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tekton-dashboard-auth-app-tekton-dashboard-9097
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.router
          portNumber: 9097
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            http_service:
              authorization_request:
                allowed_headers:
                  patterns:
                    - exact: cookie
                    - exact: X-Forwarded-Host
                    - exact: X-Forwarded-Method
                    - exact: X-Forwarded-Proto
                    - exact: X-Forwarded-Uri
                headers_to_add:
                  - key: x-eas-verify-params
                    value: >-
                      {"config_token":"..."}
              path_prefix: /envoy/verify-params-header
              server_uri:
                cluster: >-
                  outbound|80||eas-external-auth-server.external-auth-server.svc.cluster.local
                timeout: 10s
                uri: >-
                  http://eas-external-auth-server.external-auth-server.svc.cluster.local
            status_on_error:
              code: Forbidden
            with_request_body:
              allow_partial_message: true
              max_request_bytes: 4096
  workloadSelector:
    labels:
      app: tekton-dashboard

```

So I guess tekton dashboard (since v0.19) is seeing the authentication headers that `envoy.filters.http.ext_authz` is providing and causing the issue.  Any pointers on a way to workaround this ?

**Comment by AlanGreene** [comment]
I'm not very familiar with Istio but suspect it's forwarding the `Authorization` header to the upstream service which is then not recognized by Kubernetes and rejected. If there's a way to prevent this being forwarded that should resolve the issue. From a quick look at the Istio docs it looks like there may be some options depending on your version etc., either a Lua filter to remove the header after successful auth, or possibly one of the `allowed_upstream_headers`. Doing some more reading to see if I can identify a recommended pattern.

/reopen

**Comment by AlanGreene** [comment]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto

See `headers_to_remove`:

> HTTP entity headers to remove from the original request before dispatching it to the upstream. This allows the authorization service to act on auth related headers (like Authorization), process them, and consume them. Under this model, the upstream will either receive the request (if it’s authorized) or not receive it (if it’s not), but will not see headers containing authorization credentials.

**Comment by cameronbraid** [comment]
You are correct in regards to the Authorization header.  And thanks heaps for that information as it guided me to the solution - configure the external authentication service to return a custom header : `x-envoy-auth-headers-to-remove: Authorization`

So in my case, using https://github.com/travisghansen/external-auth-server I configure my clear text `x-eas-verify-params`  config as follows :

```
    eas:
      custom_service_headers:
        x-envoy-auth-headers-to-remove:
          source: static
          query_engine: static
          query: Authorization
```
