### ISSUE TITLE
Extend Tekton Dashboard operator to create Ingress endpoint on OpenShift

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#228]
Further to https://github.com/tektoncd/dashboard/issues/212 and the work to create a Tekton Dashboard operator in https://github.com/openshift/tektoncd-pipeline-operator/pull/14 and https://github.com/akihikokuroda/tektoncd-pipeline-operator/tree/dashboard, this issue extends the Tekton Dashboard Operator so as to optionally create an Ingress endpoint for the dashboard. 

The address of the Ingress endpoint that is created will need to be set as an environment variable within the dashboard unless there's a better way for the dashboard to determine the Ingress endpoint associated with its service.

**Comment by akihikokuroda** [comment]
I'll add the following ingress.  The <proxy IP> is replaced by the ProxyIP in the Install CRD for the dashboard during the install by the operator.

```    
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: tekton-dashboard
    spec:
      rules:
      - host: tekton-dashboard.<proxy IP>.nip.io
        http:
          paths:
          - backend:
              serviceName: tekton-dashboard
              servicePort: 9097
```
