### ISSUE TITLE
Skipped tasks shown as pending

### ISSUE THREAD

**Issue by larhauga** [tektoncd/dashboard#2293]
# Describe the bug

Pipelines with tasks that are skipped (like due to non master branch run) is observed to have the state of pending even though it has been skipped. This issue came to us from end-users, which did not understand why the task was still pending.

![image](https://user-images.githubusercontent.com/456305/150386900-b30fce89-af87-47d5-9b7b-9a880f083bb7.png)

# Expected behaviour
We expect the status of the skipped task to be `Skipped`; not `Pending`.

# Steps to reproduce the bug
In this case we have a `when` condition, that skipps this task if branch is main or master.
```
...
    - name: promote
      runAfter:
      - mvn-build
      taskRef:
        kind: ClusterTask
        name: # taskname
      when:
      - input: $(params.gitbranchname)
        operator: in
        values:
        - master
        - main
...
```

# Environment details

- Kubernetes Platform: EKS

- Kubernetes or OpenShift version: 1.21

- Install mode (if on OpenShift): no

- Cloud-provider/provisioner: EKS

- Versions:
   - Tekton Dashboard: 0.23.0
   
   - Tekton Pipelines: 0.31.0
   
   - Tekton Triggers: 0.18.0
   
- Install namespaces:
   - Tekton Dashboard: tekton-pipelines
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   

# Additional Info
