### ISSUE TITLE
Tekton Dashboard 401 error

### ISSUE THREAD

**Issue by Yeroha** [tektoncd/dashboard#2679]
Hello everyone. Could help me please
# Expected behavior
Tekton Dashboard should be

# Actual behaviour
We use authorization istio+oauth-proxy+keycloak. Web UI opening but we getting 401 error on endpoints
```
Request URL: https://<URL>/apis/tekton.dev/v1beta1/taskruns/
Request Method: GET
Status Code: 401
```

# Steps to reproduce the bug

1. Set roles on Keycloak
2. Set oauth-proxy2
3. Set Istio AuthorizationPolicy

# Additional info

- Kubernetes version:

  **Output of `kubectl version`:**
  ```
  kubectl version --short
  Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
  Client Version: v1.24.1
  Kustomize Version: v4.5.4
  Server Version: v1.25.4+rke2r1
  ```

- Tekton versions:
  ```
  tkn version
  Client version: 0.28.0
  Pipeline version: v0.42.0
  Triggers version: v0.22.0
  Dashboard version: v0.31.0
  ```

```
cat ext-auth-ingress-gateway.yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext-authz-oauth2-proxy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
  - to:
    - operation:
        hosts: 
        - "<SITE_URL>"
        notPaths: ["/auth/*"]
```
