### ISSUE TITLE
Dashboard step output doesn't appear when stdoutConfig or stderrConfig is used in task definition

### ISSUE THREAD

**Issue by kaktusztea** [tektoncd/dashboard#2840]
If I use `stdoutConfig` or `stderrConfig` features in my task definition at steps to redirect and collect all logs on a dedicated `logstore` workspace. In this case outputs on Tekton Dashboard also disappears unfortunately.

Is there a way to "`tee`" this output or still have the Dashboard output somehow?

# Expected behavior
Still see steps' output in Tekton Dashboard.

# Actual behaviour
No logs appear in Dashboard's task steps' output (shows only "no log available").
In case (for testing this) I use only `stdoutConfig` redirection then error outputs are there in step output, so it looks like Dashboard is tapped on `stdout` and `stderr` as well.
I can still see container outputs in Kubernetes of course, but losing Dashboard monitoring feature is less than ideal.

# Additional info

**Kubernetes version**: 1.24.2

**Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"60d6794382fe229fcf97000e8175c0315ebe8863", GitTreeState:"clean", BuildDate:"2022-09-09T08:30:58Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Tekton versions**:

```
Pipeline version: v0.42.0
Triggers version: -
Dashboard version: v0.31.0
```

### code snippet from mytask.yaml

```
- name: mystep
  image: ubuntu
  stdoutConfig:
        path: "$(workspaces.logstore.path)/task_logs/mytask/mystep.log"
  stderrConfig:
        path: "$(workspaces.logstore.path)/task_logs/mytask/mystep.log"
  script: |
{{ .Files.Get "scripts/mystep.bash-tpl" | indent 8 }}
```
