### ISSUE TITLE
Dashboard doesn't display pipelines name

### ISSUE THREAD

**Issue by mike-serchenia** [tektoncd/dashboard#2851]
# Expected behavior
Dashboard displays pipelines name using git resolver
# Actual behaviour
Dashboard doesn't display pipelines name if using git resolver  
# Steps to reproduce the bug

1. install dashboard  v0.34.0, pipelines v0.46.0
2. use the standard pipelineRef e.g.
```
  pipelineRef:
    params:
      - name: repo
        value: tekton-catalog
      - name: pathInRepo
        value: pipeline/go/0.3/go.yaml
    resolver: git
```

**Comment by AlanGreene** [comment]
Hi @mike-serchenia, thanks for opening an issue. I'm not sure I understand the bug, can you elaborate on what the issue is that you're seeing? Perhaps screenshots might help.

**Comment by mike-serchenia** [comment]
I think the problem with git resolver rather then dashboard
```
Git resolver
      taskRef:
        resolver: git
        params:
          - name: repo
            value: tkn-catalog
          - name: pathInRepo
            value: task/github-find-pr/0.1/github-find-pr.yaml
          - name: name  <<< NO SUCH OPTION
            value: hello-world
```
            
Bundle
```
  taskRef:
    resolver: bundles
    params:
    - name: bundle
      value: docker.io/ptasci67/example-oci@sha256:053a6cb9f3711d4527dd0d37ac610e8727ec0288a898d5dfbd79b25bcaa29828
    - name: name  <<< HERE
      value: hello-world
    - name: kind
      value: task
```
      
this results in pod label [tekton.dev/pipeline](http://tekton.dev/pipeline)  takes value of pipelineRun
```
tekton.dev/pipeline=python-sanity-run-68rln
tekton.dev/pipelineRun=python-sanity-run-68rln
```
