### ISSUE TITLE
Ability to select an initial namespace on GUI

### ISSUE THREAD

**Issue by achetronic** [tektoncd/dashboard#3297]
# Feature request

By default, when entering into the GUI, in the upper right selector, "All Namespaces" is selected, but when you have a giant cluster with a lot of PipelineRun resources at the same time, this seems to be slow and cause more problems when a lot of people enters at the same time

# Use case

If a flag like `--default-selected-namespace` is added, you can choose an empty namespace and force the user to select an specific one

# Alternatives

N/A

# Additional context

Latest version of everything nowadays (dashboard, pipelines, kubernetes 😄 )

**Comment by achetronic** [comment]
CC: @jdominguez408 FYI

**Comment by AlanGreene** [comment]
Hi @achetronic, thanks for the feature request. From your description it sounds like you'd benefit from disabling the 'All Namespaces' option too. This is actually possible today by setting the `namespaces` arg in the Dashboard deployment, or via the `--tenant-namespaces` option of the installer script.

This limits the displayed namespaces to only those specified, removing the 'All Namespaces' option. The namespaces are displayed in sorted order and the first one is selected by default.

Would this suit your requirements or do you still see a need for something like the 'default' flag you described?

**Comment by achetronic** [comment]
hello @AlanGreene and thanks for the answer in advance :) 

The point is that this is an entire cluster for the pipelines, so we want the ability to inspect all namespaces, as each namespace has different pipelines runs entering. But the problem is that they are too many, so if you enter in the GUI selecting "All Namespaces", multiplied by the number of users, is slowing down sometimes even the cluster

The point is that namespaces are created dynamically, so we can not select only some of them with the flag you mentioned, as I understand it's used to select only some of them. Honestly, for us the dashboard is quite good, but only lacking of a flag to not select "All Namespaces" unless you explicitly select it on the GUI

WDYT? :)

**Comment by AlanGreene** [comment]
I see, thanks for the additional context. Yes unfortunately that config won't help in the case of dynamically created namespaces.

We'll need to consider what approaches might make sense to address this type of issue and the impact they would have on other functionality. We may end up with a 'default namespace' setting as you suggested, or perhaps an entirely different solution.

Can you also provide some additional data to help understand the load you're seeing? i.e. number of concurrent users, number of namespaces, runs, etc.

**Comment by achetronic** [comment]
@AlanGreene Before throwing metrics here (let's keep this conversation clean), when the dashboard ask the backend to get `All Namespaces` PipelineRun objects, is the controller reading them from K8s APIServer in real time for each request? :)

**Comment by AlanGreene** [comment]
> is the controller reading them from K8s APIServer in real time for each request?

Short answer is yes, the Dashboard essentially acts as a thin proxy to the k8s API server.

However, there is some client-side caching in place, keyed by resource kind, namespace, and filters, valid for 5 minutes. So the first request for a particular cache key will go to the k8s API server, once that response is received the client establishes a websocket connection for real-time updates to those resources. This websocket connection is only maintained for resources relevant to the active page.

As the user navigates about the Dashboard, the client will only make requests to the backend to list resources for which it does not already have a valid cache entry. A full-page reload and some changes in network state will invalidate the cache causing the client to re-request resources for the active page.

**Comment by achetronic** [comment]
Hello there, sorry for the delay,

The issue is: the API server can be overloaded if several processes overuse it, so what worries me is if Tekton GUI flow is the following, then GUI can make API Server fall down:

Several users ---> Tekton GUI (All namespaces) --> Tekton Controller (List all pipelineruns, all namespaces [i.e 1000 resources]) ---> API Server (n* 1000) ---> GKE Repairing status

I think including this flag could make the flow lighter in this way:

Several users ---> Tekton GUI (empty namespace) --> Tekton Controller (List all pipelineruns, empty namespace [i.e 0 resources]) ---> API Server (n* 0)

Unless a user select a namespace explicitly :)

**Comment by AlanGreene** [comment]
It's worth noting that the Dashboard is not designed to be used as your primary Ci/CD interface, especially not for large numbers of users. Think of it more akin to a Tekton-flavoured version of something like the Kubernetes Dashboard (which also takes the same approach). It's not clear to me from your description if that's how you're using it but thought I should mention this.

Even if the Dashboard were to select a different namespace by default, there's nothing to stop all of your users selecting the 'All Namespaces' option manually, so I'm not sure this really addresses the problem you've described. Unless we take the same approach as the current `tenant-namespaces` option by removing the 'All Namespaces' option.

Changes around handling of default behaviour could also cause issues with URLs / bookmarkability as the current default has 'All Namespaces' selected and no namespace segment in the URL paths. If we keep 'All Namespaces', how would the Dashboard differentiate between someone loading the page with 'All Namespaces' selected and the scenario where we want the configured default to be used instead? We can't really change the current URL structure as that would be a major breaking change to users.

More thought needed to make sure we're actually addressing the problem, while avoiding creation of new issues / unwanted changes in behaviour elsewhere. Suggestions welcome of course.

**Comment by AlanGreene** [comment]
Read-only vs. read-write makes no difference here, the Dashboard is just not intended to be used by large number of users.

Providing the metrics requested earlier would be really helpful to understand the scale and extent of your usage. Perhaps there are other options that might be worthwhile exploring for similar patterns of usage as part of our longer term roadmap.

That said, I have opened a draft PR adding a default namespace config option. It will only take effect if the user visits the Dashboard root, i.e. `<dashboard-domain>/#/` (no path specified). This is the only way to add support for this feature without also removing the 'All Namespaces' option as I described in my previous comments. This means that if a user visits `<dashboard-domain>/#/pipelineruns` or a similar URL (without a namespace in the URL) directly, they will still load the matching resources for All Namespaces.

There's some additional testing required before we merge the PR, but so far it looks good.

Does this approach work for your needs given the limitation I've described?

**Comment by achetronic** [comment]
Hello :) even if this is issue was automatically closed, I wanted to document what we have finally done. 

As you said @AlanGreene adding this flag needed to add another one to remove the "all Namespaces" option in the select box. Honestly, I think supporting both them would be the perfect solution but I understand the project is a bit reluctant to add them for possible side effects to other people. I dunno exactly how adding them can affect others but I assumed I am loosing something so tried to solve this in other way

As a context, we are using Istio with Gateway API specification. Our fix is redirecting the URLs that the GUI is calling under the hoods as if they were calling the same for an specific empty namespace: `default` at this moment. We did this as follows:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tekton-dashboard-not-all-namespaces-redirect
  namespace: <whatever>
spec:
  hostnames:
  - pipelines.company.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: stable
    namespace: istio
    sectionName: https-proxy
  rules:
  - filters:
    - requestRedirect:
        path:
          replacePrefixMatch: /apis/tekton.dev/v1/namespaces/default/pipelineruns/
          type: ReplacePrefixMatch
        statusCode: 302
      type: RequestRedirect
    matches:
    - path:
        type: PathPrefix
        value: /apis/tekton.dev/v1/pipelineruns/
  - filters:
    - requestRedirect:
        path:
          replacePrefixMatch: /apis/tekton.dev/v1/namespaces/default/taskruns/
          type: ReplacePrefixMatch
        statusCode: 302
      type: RequestRedirect
    matches:
    - path:
        type: PathPrefix
        value: /apis/tekton.dev/v1/taskruns/
```

This way, the GUI reacts in the same way as if the option "All namespaces" does not exist
