### ISSUE TITLE
Add more rendering options in pipelineRun generatedName 

### ISSUE THREAD

**Issue by caiocampoos** [tektoncd/dashboard#3323]
# Feature request

We want to render links and tags on the pipeline run generated name, currently only working with alphanumeric lowercase and - characters. 

# Use case

We want to render links and tags to organize better our workflows. Something like Circleci or more custom. 

# Additional context

Something like this. 

![Screenshot 2024-02-20 at 12 08 04](https://github.com/tektoncd/dashboard/assets/27910850/87236a13-cea3-4b66-b9f9-0aa5a1ce2a07)

**Comment by AlanGreene** [comment]
Hi @caiocampoos, thanks for the feature request. Can you elaborate a bit on what exactly you're trying to do?

It would be really helpful if you could provide an example of the PipelineRun YAML, identify which piece specifically doesn't currently meet your needs, and describe how you expect it to be handled.

**Comment by caiocampoos** [comment]
@AlanGreene of course, thanks for the reply.
I am currently trying to add a link to the pull request that trigger the pipeline run, so on tekton dashboard i can easily click a link and go to github on the correct pull request.  I could not quite figure it out by the dashboard documentation how would i do that, the further i got was just displaying the ref and author of the pr in the pipeline generated name. 


```yaml
- apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pr-$(tt.params.ref)-$(tt.params.author)-
      spec:
        serviceAccountName: service-account-{{ .Values.projectName }}

        pipelineRef:
          name: {{ .Values.projectName}}-pipeline
        workspaces:
          - name: shared-data

```
