### ISSUE TITLE
Add StepActions to the Dashboard

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/dashboard#3348]
# Feature request

StepActions were released in Tekton Pipelines v0.54.0.
It would be nice to view them in the Dashboard listing all the different CRDs.
<img width="378" alt="Screenshot 2024-03-12 at 11 37 59 AM" src="https://github.com/tektoncd/dashboard/assets/11685590/11806d1b-4f6d-4215-9028-6d11b61a3f06">

# Use case

Readability and quick access to the underlying StepAction Spec.

# Alternatives

# Additional context

**Comment by AlanGreene** [comment]
Thanks for the feature request @chitrangpatel. Adding a new link to show the StepActions resources should be relatively straightforward. Would there also be changes required on the PipelineRun or TaskRun details pages to show these or are they unaffected?

**Comment by chitrangpatel** [comment]
Hi @AlanGreene 
We would not require changes on the pipelineRun side.

On the TaskRun side, it would be nice to also list any StepActions if used in-line in the TaskRun's spec. It would be found under:
```yaml
TaskRun:
spec:
  taskSpec:
    steps:
      - ref:
         name: <step-action-name>
```

On the other hand, it is also possible that the referenced Task in-turn references StepActions.
In that case, we want to list them on the `Task` details page.

```yaml
Task:
  spec:
    steps:
      - ref:
         name: stepaction-name
```

StepActions was released in 0.54.0. I think we need 6 months for review time before we can make it beta. I'm hoping to do that as soon as it's past the minimum time it needs to remain in alpha.
