### ISSUE TITLE
Add ability to disable links to resource details pages on a resource extension list page

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#3381]
# Feature request

Request from @charlesmorin, see https://tektoncd.slack.com/archives/CHTHGRQBC/p1712847670612199 (copied most relevant bits below):

is there a way in Tekton Dashboard to disable hyperlinks on list items [when using a custom extension](https://tekton.dev/docs/dashboard/extensions/)? I am trying to come up with only a list of custom items and would like to remove the hyperlink on each rows. Thank you

# Use case

We built an external queue system for our Tekton platform (dynamodb+s3), which consists on a webhook interceptor on a event listener, a golang service that handles/ingests webhook and decides if a pipelinerun must be created out of a webhook. If the cluster is too busy, we queue the item (webhook). We have a golang worker that continuously monitors the cluster capacity and trigger pipelines when there’s room (firing off a webhook to another event listener which will trigger pipelineruns). Upon successful dispatch of a queued webhook, the worker pops the items out of the queue.
We want devs to see the current queue just like they have on Jenkins (what the repository is, the PR number, the priority in queue, etc), so we leveraged the custom extension to add a PipelineRuns Queue item in the sidebar. It’s not meant to ne sophisticated UI by any means. We just need a pretty simple list of queued items so people can see what’s pending in the queue. Each rows in the page has an hyperlink on it, which you can imagine gives a 404 since we’re not displaying a resource per se.
Let me know if you have ideas as for how I could have more control on the page layout, if that’s possible. Thanks Alan!

here’s what I got in my cluster:
```yaml
---
apiVersion: dashboard.tekton.dev/v1alpha1
kind: Extension
metadata:
  name: queuedpipelineruns
spec:
  apiVersion: tekton.company.com/v1
  name: queuedpipelineruns
  displayname: PipelineRuns Queue
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queuedpipelineruns.tekton.company.com
spec:
  group: tekton.company.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
  scope: Cluster
  names:
    plural: queuedpipelineruns
    singular: queuedpipelinerun
    kind: QueuedPipelineRun
    shortNames:
    - qpr
```

then we leverage istio to proxy that specific endpoint so that our backend returns what we need in the format the dashboard expects.

# Alternatives

# Additional context
