### ISSUE TITLE
Dashboard 403 on tekton-dashboard deployed to own namespace on OKD 3.11

### ISSUE THREAD

**Issue by dacleyra** [tektoncd/dashboard#364]
# Expected Behavior

Dashboard is accessible after deployment on OKD 3.11

# Actual Behavior

403

# Steps to Reproduce the Problem

1. OKD 3.11 cluster
2. Install to my own namespace
```
curl -L https://github.com/tektoncd/dashboard/releases/download/v0/gcr-tekton-dashboard.yaml \
 | sed 's/namespace: tekton-pipelines/namespace: kabanero/' \
 | kubectl apply --filename -
```
3. Create a route to access dashboard
```
oc expose service tekton-dashboard \
  -n kabanero \
  --name "tekton-dashboard" \
  --port="http" \
  --hostname=tekton-dashboard.${openshift_master_default_subdomain}
```
4. Accessing dashboard via Route (or port-forward) results in 403 back from tekton-dashboard itself

# Additional Info

Fix by adding to ClusterRole
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-dashboard-minimal
  namespace: kabanero
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
```
