### ISSUE TITLE
FR: responsively rendered updates to pipeline status

### ISSUE THREAD

**Issue by castlemilk** [tektoncd/dashboard#383]
It would be nice if the status of `Task`/`PipelineRun` was more up-to-date when changes occur. I couldn't see any polling occurring to check if updates had occurred in the given tasks for a `PipelineRun`.

Potentially use something like `redux-sagas`, polling the required API's and reconcile pipeline/task updates in the UI. Alternatively a websocket based approach could be used to push updates to the client more reactively?

**Comment by AlanGreene** [comment]
@castlemilk the dashboard does use a websocket to receive updates to the status of the resources which should be reflected in the UI. This currently includes all Tekton resources, as well as secrets and namespaces.

You should see a ws connection to `/v1/websockets/resources`.

If you're not seeing these updates as expected can you provide more details about your environment?

- which platform? (GKE, OpenShift, IKS, etc.)
- kubernetes version
- tektoncd/pipeline version
- tektoncd/dashboard version
- browser
- how are you accessing the dashboard? (kube proxy, port-forward, etc.)

**Comment by castlemilk** [comment]
Hi @AlanGreene,

I'm enabling ingress into the dashboard via istio with the following vs:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tekton-dashboard
spec:
  gateways:
  - knative-ingress-gateway.knative-serving.svc.cluster.local
  - mesh
  hosts:
  - tekton-dashboard.example.com
  http:
  - route:
    - destination:
        host: tekton-dashboard.tekton-pipelines.svc.cluster.local
        port:
          number: 9097
    websocketUpgrade: true
```

I can see successful websocket connections via logs but cannot see updates occuring reliably when tasks transition from `Waiting` to `Running`. I'm having to refresh the browser to see updates. 

This is what would be shown without manually updating:

![image](https://user-images.githubusercontent.com/7474316/62045244-377f7480-b248-11e9-89e2-77b8ddb9a93c.png)

then after a manual refresh it's updated to the following:

![image](https://user-images.githubusercontent.com/7474316/62045300-6b5a9a00-b248-11e9-82f0-deb9d650931c.png)


Platform: GKE
kubernetes version: v1.13.7-gke.8
tektoncd/pipeline version: 0.5.2
tektoncd/dashboard version: tekton-nightly/dashboard@sha256:01351977d4d883256d7a4d813fcb0afa0ced915f4a8fc76145580507bbdd362e
browser: chrome
access mode: via istio ingressgateway
