### ISSUE TITLE
Add Ingress for dashboard

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#387]
# Expected Behavior
We could have an ingress rule that's named `tekton-dashboard`, offered up at our get Ingress API (specifically, `v1/namespaces/tekton-pipelines/ingress`).

Once https://github.com/tektoncd/dashboard/pull/386 is merged, users would be able to programatically find our Ingress endpoint from our API.

With the changes I'm proposing there'll be an Ingress endpoint even if:
a) the operator changes to include addons and thus the dashboard are not yet merged and generally available
b) the user hasn't installed the dashboard via an operator

Once the operator changes are merged (see @akihikokuroda's work over at https://github.com/tektoncd/dashboard/issues/228#issuecomment-516070816), I **believe** it will create a different kind of Ingress anyway. If I'm mistaken, we could theoretically remove this (easy to add anyway) Ingress in favour of it.

# Actual Behavior
We don't have this and I know of another project (Eclipse Codewind) that's looking to offer a button displaying our main dashboard endpoint.

# Additional Info
The Ingress definition should be:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  rules:
  - host: <dashboard-host> (e.g. *your externally available IP address*.nip.io)
    http:
      paths:
      - backend:
          serviceName: tekton-dashboard
          servicePort: 9097
```

The name is important as this is what our get Ingress API returns.

The host field would need be provided after the main install (e.g. via a kubectl patch)  to specify the correct host. So if we are to add said change, document this in the main install readme and provide a concise patch command.
