### ISSUE TITLE
Add possibility to nicely render and edit multiline strings in Tekton Dashboard GUI for TaskRun specs

### ISSUE THREAD

**Issue by kseniyashaydurova** [tektoncd/dashboard#4071]
# Feature request

Add possibility to nicely render and edit multiline strings in Tekton Dashboard GUI for TaskRun specs.
Currently it is hard to pass and process multiline strings and arrays in Tekton Dashboard TaskRun parameters (which are added automatically from selected Task).

# Use case

We specify k8s `command` (array type), `tolerations` (string type) and `affinity` (string type) as Task parameters, from gitops side it looks ok. But if we need to edit it in Tekton Dashboard GUI, it becomes very hard and not user friendly

![Image](https://github.com/user-attachments/assets/d769669a-39e9-48b1-852e-bc487b555f66)

# Alternatives

It would be great if multiline string params look like multilines in Tekton Dashboard GUI too.

# Additional context

```
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test
  namespace: test
spec:
  description: The test task
  params:
  - default: |
      - bash
      - -c
      - |
        sleep infinity
    name: command
    type: string
  - default: |
      - effect: NoSchedule
        key: workload
        operator: Equal
        value: test
    name: tolerations
    type: string
  - default: |
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: workload
              operator: In
              values:
              - test
    name: affinity
    type: string
  steps:
  - env:
    - name: COMMAND
      value: $(params.command)
    - name: TOLERATIONS_YAML
      value: $(params.tolerations)
    - name: AFFINITY_YAML
      value: $(params.affinity)
    image: bash:latest
    imagePullPolicy: Always
    name: test
    script: |
      #!/usr/bin/env bash
      echo "Hello world"
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsNonRoot: true
```
