### ISSUE TITLE
Password in clear text displayed on Secrets page 

### ISSUE THREAD

**Issue by bconey** [tektoncd/dashboard#511]
# Expected Behavior
After creating a secret, it would be displayed on the Secrets panel but the annotations displayed would not include sensitive information such as password in clear text; somehow those could be filtered out.

# Actual Behavior
The secret is displayed in the secrets panel with the password is in clear text.

# Steps to Reproduce the Problem

1. Ran the command `oc apply -n <namespace> -f <secrets_yaml_file>`
2. Secret was successfully created
3. View secret in Secrets panel and note the annotation entry for it.
3.

# Additional Info
A template of the secrets_yaml_file used was:

```
apiVersion: v1
kind: Secret
metadata:
  name: secret-test2
  annotations:
    tekton.dev/git-0: "<git server url>"
type: kubernetes.io/basic-auth
stringData:
  username: "token"
  password: "<token>"
```
