### ISSUE TITLE
Rebuild a PipelineRun leads to an error in the Dashboard

### ISSUE THREAD

**Issue by maxveit** [tektoncd/dashboard#539]
# Expected Behavior
"Rebuild" of an PipelineRun leads to the execution of a rebuild.

# Actual Behavior
"Rebuild" of an PipelineRun leads to an error:
```
{
   "level":"error",
   "msg":"an error occurred rebuilding the PipelineRun java-microprofile-build-deploy-pipeline-run-1569231654541 in namespace kabanero: Internal error occurred: admission webhook \"webhook.tekton.dev\" denied the request: mutation failed: Invalid resource name: length must be no more than 63 characters: metadata.name"
}
```

# Steps to Reproduce the Problem
1. Fresh install of Kabanero
2. Create a Git Resource, I used the following:
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: stocktrader-trader-git
  namespace: kabanero
spec:
  type: git
  params:
    - name: url
      value: https://github.com/IBMStockTrader/trader.git
    - name: revision
      value: master
```
3. Create a Docker Resource, I used the following (ImageStream created beforehand):
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: stocktrader-trader-image
  namespace: kabanero
spec:
  type: image
  params:
    - name: url
      value: docker-registry.default.svc:5000/kabanero/stocktrader-trader
```
4. Create a PipelineRun with the above parameters and the microprofile pipeline (no ServiceAccount)
5. Click Rebuild

# Additional Info
n/a
