### ISSUE TITLE
Kabanero Pipelinerun pod in Tekton Dashboard does not show log error of pv.yaml missing which is pre-requisite of Kabanero

### ISSUE THREAD

**Issue by aadeshpa** [tektoncd/dashboard#560]
# Expected Behavior
Kabanero Pipelinerun requires `pv.yaml` to be applied before pipelinerun happens.
If end user has not applied this resource and if webhook triggers the pipelinerun , in Tekton dashboard user should see error message for missing `pv.yaml` resource in that cluster.

Hence expected behavior is to see some error message for pv.yaml missing.

# Actual Behavior
In Tekton dashboard pipelinerun shows the build task pod keeps on loading infinetly without showing any logs, because the pod itself is not started correctly due to the missing pv.yaml.
![pv-yaml-missing](https://user-images.githubusercontent.com/53223993/65630691-ea97f000-dfa3-11e9-9e2a-c36f73812f5f.jpg)

 

# Steps to Reproduce the Problem

1. Do not apply `pv.yaml` file to the cluster 
2.Create a Webhook in the GitHub repository of the application
3. Create a pull request in Github repository used in step 1
4. Observe the logs of build task pod in Tekton Dashboard for the selected pipeline to be run.

# Additional Info

  #Possible Solution
1. We found that in the cluster by running the below command we get the details of the `pv.yaml` is missing:-

`kubectl describe pod build-task-pod-xxx`

sample output:-
```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  3m (x716 over 38m)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 2 times)
```

2. Or we also found that if you describe the pipelinerun as per below command you get the status and error message

`kubectl get pipelineruns/pipelinerun-name -o yaml`

Sample output:

```
status:
  conditions:
  - lastTransitionTime: 2019-09-25T18:13:08Z
    message: Not all Tasks in the Pipeline have finished executing
    reason: Running
    status: Unknown
    type: Succeeded
  startTime: 2019-09-25T18:13:12Z
  taskRuns:
    kab-nodejs-express-wbh-2-1569435188-build-task-zxpn2:
      pipelineTaskName: build-task
      status:
        conditions:
        - lastTransitionTime: 2019-09-25T18:13:12Z
          message: 'pod status "PodScheduled":"False"; message: "pod has unbound PersistentVolumeClaims
            (repeated 2 times)"'
          reason: Pending
          status: Unknown
          type: Succeeded
        podName: kab-nodejs-express-wbh-2-1569435188-build-task-zxpn2-pod-100978
        startTime: 2019-09-25T18:13:12Z
```
