### ISSUE TITLE
Dashboard extension support

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#7]
It would be great if the dashboard offered an extension mechanism. 'Extensions' could be packaged behind Kube services, with labels of the form, 
```
label: tekton-dashboard-extension: true
label: tekton-dashboard-endpoints: greatThings
```
The extension should then be able to supply panelling into a react component on the dashboard - perhaps a new tab? - whose .js code would be able to interact with the extension via the /greatThings proxied endpoint. Extensions could support managing web hooks, log archiving, or integrations with other third party product.

**Comment by akihikokuroda** [comment]
I can not assign this to myself but I'll work for this.

**Comment by akihikokuroda** [comment]
The service that has the following items is added as the back-end extension.
```  
annotations:
    tekton-dashboard-endpoints: <path for the extension>
  labels:
    tekton-dashboard-extension: "true"
```
PR: https://github.com/tektoncd/dashboard/pull/34
