### ISSUE TITLE
TaskRuns page is broken if a TaskRun with an embedded TaskSpec is present

### ISSUE THREAD

**Issue by bashofmann** [tektoncd/dashboard#821]
# Expected Behavior
The TaskRuns page should list all TaskRuns regardless if they contain a TaskRef or an embedded TaskSpec (see https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#specifying-a-task).

# Actual Behavior
As soon as there is a TaskRun with an embedded TaskSpec is present the dashboard throws the following error and the TaskRuns list is not displayed:

```
backend.js:6 TypeError: Cannot read property 'name' of undefined
    at main.6b5f8a5f6f5f5867f66c.js:1
    at Array.map (<anonymous>)
    at TaskRuns.value (main.6b5f8a5f6f5f5867f66c.js:1)
    at go (vendors.b5d0840470f9aef60e02.js:91)
    at bo (vendors.b5d0840470f9aef60e02.js:91)
    at Gc (vendors.b5d0840470f9aef60e02.js:91)
    at zc (vendors.b5d0840470f9aef60e02.js:91)
    at Rc (vendors.b5d0840470f9aef60e02.js:91)
    at Ac (vendors.b5d0840470f9aef60e02.js:91)
    at vendors.b5d0840470f9aef60e02.js:91
```

<img width="963" alt="Bildschirmfoto 2019-12-10 um 21 54 13" src="https://user-images.githubusercontent.com/243056/70568177-b346e180-1b97-11ea-826c-af21480e911e.png">

# Steps to Reproduce the Problem

1. Create a TestRun with an embedded TaskSpec:
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: testrun
  namespace: default
spec:
  inputs: {}
  outputs: {}
  podTemplate: {}
  taskSpec:
    inputs: {}
    steps:
    - args:
      - -c
      - date
      command:
      - bash
      image: ubuntu
      name: test
      resources: {}
```
2. Go to "TaskRuns" in the dashboard.

# Additional Info
Running tektoncd/dashboard 0.3.0.
