### ISSUE TITLE
Tasks should be sorted in Pipeline spec order not alphabetically

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#932]
# Expected behavior
Tasks should be sorted by the order they are defined in the Pipeline, not alphabetically

# Actual behavior
They're sorted alphabetically

# Steps to reproduce the problem

1. Create a PipelineRun with at least three tasks
2. Refresh the page once all tasks complete and see they're ordered alphabetically

# Environment (e.g. Docker Desktop, OpenShift)
All

# Tekton Pipelines version (e.g. 0.9.2, 0.8.0, master)
Any

# Tekton Triggers version (e.g. 0.2, 0.1, master)
Any

# Tekton Dashboard version (e.g. 0.4.0, 0.3.0, master)
All

**Comment by a-roberts** [comment]
@AlanGreene do you think this'd be particularly hard to do? I've noticed we've got a sorting by time already on the TaskRuns page, for full disclosure it's being asked for as a useful feature to have for the upcoming release of the Kabanero project as there's a validate task that actually happens first, but it's displayed at the bottom

**Comment by AlanGreene** [comment]
hrmm displaying them alphabetically (the current mystery behaviour we have no explicit code for...) is definitely not right, but I'm not sure if sorting by timestamp is right either as it won't be consistent across multiple PipelineRuns for the same Pipeline where some Tasks are run in parallel.

Ideally we'd display them in topologically sorted order (walk the DAG essentially), but this would take a bit of work considering the current approach to processing the data.

Maybe we could display them in the order they're defined in the Pipeline definition? That would be relatively simple and we already do it for steps so could take a similar approach.

If we do want to sort by timestamp it would be simple enough to do in either the PipelineRun or TaskTree component assuming the metadata including timestamps is available at those points.

**Comment by a-roberts** [comment]
> hrmm displaying them alphabetically (the current mystery behaviour we have no explicit code for...) is definitely not right, but I'm not sure if sorting by timestamp is right either as it won't be consistent across multiple PipelineRuns for the same Pipeline where some Tasks are run in parallel.
> 
> Ideally we'd display them in topologically sorted order (walk the DAG essentially), but this would take a bit of work considering the current approach to processing the data.
> 
> Maybe we could display them in the order they're defined in the Pipeline definition? That would be relatively simple and we already do it for steps so could take a similar approach.
> 
> If we do want to sort by timestamp it would be simple enough to do in either the PipelineRun or TaskTree component assuming the metadata including timestamps is available at those points.

Good points, yeah I like the idea of doing it based on the position in the Pipeline for now, I'm wary there's run after and folks needn't place things in order really but at least it'll be done in a well defined way and to some specification

**Comment by anneqm** [comment]
consensus here:  prefer displaying in the order defined in the Pipeline definition rather than by timestamp.  Can we update the issue description? :)

**Comment by a-roberts** [comment]
> consensus here: prefer displaying in the order defined in the Pipeline definition rather than by timestamp. Can we update the issue description? :)

Done

**Comment by a-roberts** [comment]
Right, got a test Pipeline, PipelineRun and some tasks, actually fixing the code now

```
---
  apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    name: test-pipeline
    namespace: tekton-pipelines
  spec:
    tasks:
      - name: b-task
        taskRef:
          kind: Task
          name: step-b-task
      - name: c-task
        taskRef:
          kind: Task
          name: step-c-task
      - name: a-task
        taskRef:
          kind: Task
          name: step-a-task
  ```

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: test-pipelinerun
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: test-pipeline
```

```
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: step-b-task
  namespace: tekton-pipelines
spec:
  steps:
    - name: step-b-task-step
      image: ubuntu
      script: ls
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: step-a-task
  namespace: tekton-pipelines
spec:
  steps:
    - name: step-a-task-step
      image: ubuntu
      script: ls
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: step-c-task
  namespace: tekton-pipelines
spec:
  steps:
    - name: step-c-task-step
      image: ubuntu
      script: ls
```

Indeed this gives 
![image](https://user-images.githubusercontent.com/12814972/74926580-05915380-53ce-11ea-93b6-5cb8d167906c.png) currently
